name: Build Flutter APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'
      
      - name: Build APK
        run: |
          # Unzip project
          unzip -q BASE_METALZ.zip
          # Cari folder hasil unzip (biasanya BASE_METALZ)
          cd BASE_METALZ
          # Install dependencies
          flutter pub get
          # Build APK
          flutter build apk --release
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-release-apk
          path: BASE_METALZ/build/app/outputs/flutter-apk/app-release.apk
